### ISSUE TITLE
余烬复燃的〝自动方块破坏器〞在FTB的领地内没有权限。

### ISSUE THREAD

**Issue by huangsijun17** [CatServer/CatServer-Pro#2]
请问，应该给fakeplayer添加哪个权限？谢谢。

自动方块破坏器
https://www.mcmod.cn/item/47357.html

**Comment by IceCream-Open** [comment]
自动方块破坏器 无法破坏方块是因为 内部为了权限兼容采用了破坏事件以检测方块是否被保护。
FTB领地没有发现限制方块破坏器的情况。

由于Forge事件会被广播至Bukkit，推测是由于Bukkit 插件拦截的事件。
可能造成问题的插件：AuthMe
解决办法：
向 AuthMe 插件的 config.yml 中的 UnrestrictedName 节点，添加 embers_breaker。

![image](https://user-images.githubusercontent.com/32815944/68753550-33813200-0640-11ea-97f1-2b8e01f7deac.png)
